# Generated by Django 5.2.5 on 2025-08-14 09:23

import django.contrib.postgres.indexes
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[("tech", "Tech"), ("paper", "Paper")], max_length=32
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title", "content"], name="posts_post_title_c5d547_gin"
                    )
                ],
            },
        ),
    ]
