# Generated by Django 5.2 on 2026-01-23 11:11

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-date"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章管理",
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_title_gin",
            old_name="posts_post_title_c5d547_gin",
        ),
        migrations.AddField(
            model_name="post",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="用于去重检测",
                max_length=64,
                verbose_name="内容哈希",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("tech", "技术文章"), ("paper", "论文笔记")],
                max_length=32,
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="Markdown 格式", verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(verbose_name="发布日期"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, help_text="文章简介", verbose_name="摘要"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True, verbose_name="已发布"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                help_text="用于生成文章链接", unique=True, verbose_name="URL 别名"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="标签",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="文章标题", max_length=255, verbose_name="标题"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
