# Generated by Django 5.2 on 2026-02-03 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_add_content_hash"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="系列的显示名称",
                        max_length=255,
                        verbose_name="系列标题",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="用于生成系列链接",
                        unique=True,
                        verbose_name="URL 别名",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="系列的详细介绍", verbose_name="系列简介"
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        help_text="系列封面图片 URL（可选）",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="数字越小越靠前，用于首页展示顺序",
                        verbose_name="排序权重",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="是否在首页显示",
                        verbose_name="首页推荐",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系列",
                "verbose_name_plural": "系列管理",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="series_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="在系列中的顺序，数字越小越靠前",
                null=True,
                verbose_name="系列内排序",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="series",
            field=models.ForeignKey(
                blank=True,
                help_text="文章所属的系列/合集",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.series",
                verbose_name="所属系列",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("series__isnull", False), ("series_order__isnull", False)
                ),
                fields=("series", "series_order"),
                name="unique_series_order",
            ),
        ),
    ]
