# Generated by Django 5.2 on 2026-03-23 03:02

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_migrate_category_values"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="多个标签请用英文逗号「,」分隔；单个标签内可以包含空格。示例：deep learning, pytorch",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="标签",
            ),
        ),
    ]
