# Generated by Django 5.2 on 2026-04-11 13:13

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="category_filter",
        ),
        migrations.RemoveField(
            model_name="series",
            name="tag",
        ),
        migrations.AlterField(
            model_name="series",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="上传封面图片（支持文件选择或粘贴上传）",
                upload_to=posts.models.series_cover_upload_path,
                verbose_name="封面图片",
            ),
        ),
    ]
