# Generated by Django 5.2 on 2026-08-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_refactor_series_to_fk"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="posts_post_title_gin",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["published", "date"], name="posts_post_pub_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category", "published", "date"], name="posts_post_cat_pub_idx"
            ),
        ),
    ]
